server:
  port: 8080
spring:
  application:
    name: cloud-consumer-order

# 配置注册中心 eureka
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka