server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0~1之间，1表示全部采样
      probability: 1

  #数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://112.124.10.0:3306/cloud2022
      username: root
      password: Zxcv0812.

      #配置连接池
      max-active: 20
      initial-size: 1
      min-idle: 5
      max-wait: 60000 #1 min
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000 #5 min

  cache:
    type: generic

#mybatis
mybatis:
  mapperLocations: classpath:/mapper/*.xml

# 配置注册中心 eureka
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka